### ISSUE TITLE
Dépendance

### ISSUE THREAD

**Issue by mopmop682** [jordanbonaldi/Linaris-PvPSwap#1]
Bonjour, 

Je ne trouve pas ces dépendances (fr.icrotz.gameapi.Game) sur votre GitHub sont elle disponible au publique ou pas ? 

Cordialement.

**Comment by jordanbonaldi** [comment]
C’est cette API, elle devrait être compatible.
https://github.com/jordanbonaldi/Linaris-GameAPI

**Comment by Math1995x** [comment]
@jordanbonaldi hey je cherche aussi le dépendance car dans la dépendance du dessus il n'y pas tout et c'est d'ailleurs pas les même package

**Comment by jordanbonaldi** [comment]
Il faut utiliser celles-ci
https://github.com/jordanbonaldi/Linaris-API/blob/master/src/main/java/net/neferett/linaris/BukkitAPI.java
https://github.com/jordanbonaldi/Linaris-GameAPI/tree/master/src/net/neferett/gameapi

Je pense qu'il faut juste remplacer fr.icrotz par net.neferett, j'ai pas du migrer le pvpswap la, je crois qu'on utilisait l'autre (https://github.com/jordanbonaldi/Linaris-PvPSwap2/tree/master/src/net/neferett/linaris/pvpswap)
